---
title: "류경민"
output: html_document
---

```{r }
library(ggplot2)
library(prob)
library(gridExtra)

```

## 카이분포 ##

```{r}
n1 <- 1000
df1 <- 10
ch.2.mean <- rep(NA, n1)
ch.4.mean <- rep(NA, n1)
ch.16.mean <- rep(NA, n1)
ch.64.mean <- rep(NA, n1)

for(i in 1:n1) {
  ch.2.mean[i] <- mean(rchisq(2, df=df1))
  ch.4.mean[i] <- mean(rchisq(4, df=df1))
  ch.16.mean[i] <- mean(rchisq(16, df=df1))
  ch.64.mean[i] <- mean(rchisq(64, df=df1))
}


m1 <- df1
s1 <- sqrt(2 * df1)
```

## 그래프

```{r}
par(mfrow=c(2,2), oma = c(0, 0, 2, 0))
hist(ch.2.mean, prob=T, main="표본 크기 : 2", 
     ylab="", xlab="", col="orange", border="red")
x1 <- seq(min(ch.2.mean), max(ch.2.mean), length=1000)
y1 <- dnorm(x=x1, mean=m1, sd=s1/sqrt(2))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(ch.4.mean, prob=T, main="표본 크기 : 4", 
     ylab="", xlab="", col="orange", border="red")
x2 <- seq(min(ch.4.mean), max(ch.4.mean), length=1000)
y2 <- dnorm(x=x2, mean=m1, sd=s1/sqrt(4))
lines(x2, y2, lty=2, lwd=2, col="blue")

hist(ch.16.mean, prob=T, main="표본 크기 : 16", 
     ylab="", xlab="", col="orange", border="red")
x3 <- seq(min(ch.16.mean), max(ch.16.mean), length=1000)
y3 <- dnorm(x=x3, mean=m1, sd=s1/sqrt(16))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(ch.64.mean, prob=T, main="표본 크기 : 64", 
     ylab="", xlab="", col="orange", border="red")
x4 <- seq(min(ch.64.mean), max(ch.64.mean), length=1000)
y4 <- dnorm(x=x4, mean=m1, sd=s1/sqrt(64))
lines(x4, y4, lty=2, lwd=2, col="blue")

mtext("카이 분포(df=10인 경우)", outer = TRUE, cex = 1.2)
```

## T 분포 ##

```{r}
n <- 1000
df <- 30
t.2.mean <- rep(NA, n)
t.4.mean <- rep(NA, n)
t.8.mean <- rep(NA, n)
t.16.mean <- rep(NA, n)


for(i in 1:n) {
  t.2.mean[i] <- mean(rt(2, df=df))
  t.4.mean[i] <- mean(rt(4, df=df))
  t.8.mean[i] <- mean(rt(8, df=df))
  t.16.mean[i] <- mean(rt(16, df=df))
}

m <- 0
s <- sqrt(df / (df - 2))

```

## 그래프 ##
```{r}
par(mfrow=c(2,2), oma = c(0, 0, 2, 0))
hist(t.2.mean, prob=T, main="표본 크기 : 2", 
     ylab="", xlab="", col="orange", border="red")
x1 <- seq(min(t.2.mean), max(t.2.mean), length=1000)
y1 <- dnorm(x=x1, mean=m, sd=s/sqrt(2))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(t.4.mean, prob=T, main="표본 크기 : 4", 
     ylab="", xlab="", col="orange", border="red")
x2 <- seq(min(t.4.mean), max(t.4.mean), length=1000)
y2 <- dnorm(x=x2, mean=m, sd=s/sqrt(4))
lines(x2, y2, lty=2, lwd=2, col="blue")

hist(t.8.mean, prob=T, main="표본 크기 : 8", 
     ylab="", xlab="", col="orange", border="red")
x3 <- seq(min(t.8.mean), max(t.8.mean), length=1000)
y3 <- dnorm(x=x3, mean=m, sd=s/sqrt(8))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(t.16.mean, prob=T, main="표본 크기 : 16", 
     xlim=c(-2,2), ylim=c(0,0.9), 
     ylab="", xlab="", col="orange", border="red")
x4 <- seq(min(t.16.mean), max(t.16.mean), length=1000)
y4 <- dnorm(x=x4, mean=m, sd=s/sqrt(16))
lines(x4, y4, lty=2, lwd=2, col="blue")

mtext("T 분포(df=30인 경우)", outer = TRUE, cex = 1.2)
```

## F 분포 ##

```{r}
n2 <- 1000
df01 <- 10; df02 <- 20
f.2.mean <- rep(NA, n2)
f.4.mean <- rep(NA, n2)
f.8.mean <- rep(NA, n2)
f.16.mean <- rep(NA, n2)


for(i in 1:n2) {
  f.2.mean[i] <- mean(rf(2, df1=df01, df2=df02))
  f.4.mean[i] <- mean(rf(4, df1=df01, df2=df02))
  f.8.mean[i] <- mean(rf(8, df1=df01, df2=df02))
  f.16.mean[i] <- mean(rf(16, df1=df01, df2=df02))
}


m2 <- df02 / (df02 - 2)
s2 <- sqrt(2 * df02^2 * (df01+df02-2) /(df01 * (df02-2)^2 * (df02-4)))

```

## 그래프 ##
```{r}
par(mfrow=c(2,2), oma = c(0, 0, 2, 0))
hist(f.2.mean, prob=T, main="표본 크기 : 2", 
     xlim=c(0,10),
     ylab="", xlab="", col="orange", border="red")
x1 <- seq(min(f.4.mean), max(f.4.mean), length=1000)
y1 <- dnorm(x=x1, mean=m2, sd=s2/sqrt(4))
lines(x1, y1, lty=2, lwd=2, col="blue")

hist(f.4.mean, prob=T, main="표본 크기 : 4", 
     xlim=c(0,6),
     ylab="", xlab="", col="orange", border="red")
x2 <- seq(min(f.4.mean), max(f.4.mean), length=1000)
y2 <- dnorm(x=x2, mean=m2, sd=s2/sqrt(4))
lines(x2, y2, lty=2, lwd=2, col="blue")

hist(f.8.mean, prob=T, main="표본 크기 : 8", 
     xlim=c(0.4,4),
     ylab="", xlab="", col="orange", border="red")
x3 <- seq(min(f.8.mean), max(f.8.mean), length=1000)
y3 <- dnorm(x=x3, mean=m2, sd=s2/sqrt(8))
lines(x3, y3, lty=2, lwd=2, col="blue")

hist(f.16.mean, prob=T, main="표본 크기 : 16", 
     xlim=c(0.8,3),
     ylab="", xlab="", col="orange", border="red")
x4 <- seq(min(f.16.mean), max(f.16.mean), length=1000)
y4 <- dnorm(x=x4, mean=m2, sd=s2/sqrt(16))
lines(x4, y4, lty=2, lwd=2, col="blue")

mtext("F 분포(df1=10, df5=20인 경우)", outer = TRUE, cex = 1.2)

```
